### ISSUE TITLE
Custom tools in depth profile window are updating one click behind

### ISSUE THREAD

**Issue by aleekaup2** [JYU-IBA/potku#113]
### Reproduction

For example when using the Limit setting tool
1. Select limit setting tool
2. Select lower and upper limits -> concentrations are correct
3. Select new lower and upper limits -> concentrations are wrong
4. Select other limit again -> concentrations update to correct value

Also the changes made in the "graph's element settings" dialog are not visible in the graph until another click

**Comment by jussiks** [comment]
5befd96 should fix the issue with legend box. Depth profile widget uses `draw_and_flush` decorator to update the legend after setting new values. Because the widget is not a GraphWrapper instance,  `getattr(canvas_wrapper, "do_flush", False)` always return false and so the legend was not updated until later.
This was a rather quick fix so I am not sure if there is still need to fix something else.

**Comment by jussiks** [comment]
Could you check #117 and see if the depth profile works okay?

**Comment by aleekaup2** [comment]
#117 fixes this
