### ISSUE TITLE
Sum spectrum disappears from the screen when restarting Potku

### ISSUE THREAD

**Issue by jkpnen** [JYU-IBA/potku#218]
Potku should remember the recent sum spectrum and show it after restart

**Comment by tpitkanen** [comment]
I think Potku just recalculates all spectra etc. when opening a Measurement/Simulation, that's why opening them is slow. The progress bar should help find where those calls happen: its values are manually set at specific points in the loading progress.

A more sensible option would be to use the spectra files to avoid recalculation, but the files probably don't have enough information to reconstruct the objects used by Potku.

One option would be to use [pickle](https://docs.python.org/3.6/library/pickle.html) to save and load all the objects, but cache invalidation (when is the object stale) etc. can be complicated.

Summary: find where Potku recalculates stuff and add sum spectra generation calls there.
