### ISSUE TITLE
PyInstaller does not bundle all binaries

### ISSUE THREAD

**Issue by tutapitk** [JYU-IBA/potku#61]
# Decription

PyInstaller does not package the following required files from `potku/external/bin` to `potku/dist/potku/external/bin/`:
- awk (see also #60)
- coinc
- jibal_bootstrap
- jibaltool

The files are correctly compiled and can be found in `potku/external/bin`, but they are not added to the package for some reason.

The issue affects all released bundles from 2020-07-01 to 2020-08-12 (present day), 2020-04-10 version is not affected. It occurs on all three supported OS platforms.

# Reproduction

Create a bundle as described in README. The problem occurs on the `pipenv run create_bundle.bat` (or `pipenv run create_bundle.sh`) step.

# Workarounds

Manually copy the missing files to release packages. Mention this in README.

**Comment by jussiks** [comment]
I'll reopen this issue. The problem is due to incorrect glob pattern in the .spec file:
https://github.com/JYU-IBA/potku/blob/115c02c6327374cae1e2e58bc384a9b01457dd3f/potku.spec#L47-L49

Fix would be to switch to a loop like this:
````
bins = [
    (f"external/bin/{file.name}", f"external/bin/{file.name}")
    for file in os.scandir("external/bin")
    if file.name != "jibal.conf"
]

a = Analysis(
    ["potku.py"],
     pathex=[],
     binaries=bins,`
    ...
````

Need to test this on all platforms (macOS version seems to be especially picky about which files can be added as binaries).  Readme should be updated as well.
